### ISSUE TITLE
Thank to you for having computed the table but what for the results of the computed qubits from the factorization ?

### ISSUE THREAD

**Issue by EdernOllivier** [ElieGouzien/factoring_with_memory#2]
Dear Elie, I suggest to you to compute the numbers of quantum in the table or in a file, I don't see them, maybe that it is too difficult for the processor with the memory, well I am happy with such a table. Regards, Edern Ollivier.

**Comment by EdernOllivier** [comment]
Dear Elie, I have been looking at the tetrahedron, funny, I can see the qubits in the place of the geometric arraignments. How much time to do this ? Regards, Edern Ollivier.

**Comment by ElieGouzien** [comment]
To make things clear, this code does not factor a 2048-bit RSA number, but evaluates the resources required to run such factorisation on a quantum computer made with a small quantum processor and a quantum memory (that we don't have for now).

With regard to your second comment, this place is intended for reporting issues on the code, or suggesting improvement, not for generic comments, so please do not spam it with remarks (even when there are nice). Also, qubits are represented by the elementary tetrahedrons, not by the vertices.

**Comment by EdernOllivier** [comment]
Dear Elie, thanks to you very much for the comment, this is not really funny, it takes a long time to compute the table, indeed, I appreciate that you have done it. Best regards, Edern Ollivier.
